#
# Copyright (c) 2021-2025 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Pull Request Check

# Trigger the workflow on pull request
on: [pull_request]

jobs:
  build_base_ubi9_image:
    name: Build base ubi9 image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Free runner space
        run: |
          sudo rm -rf /usr/local/lib/android
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Docker Build & Push Base Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: base/ubi9
          platforms: linux/amd64, linux/arm64
          tags: quay.io/abazko/base-developer-image:pr-${{env._PR_NUMBER}}
      - name: Update Universal Developer Image Dockerfile
        run: sed "s|FROM quay.io/abazko/base-developer-image:ubi9-latest|FROM quay.io/abazko/base-developer-image:pr-${{env._PR_NUMBER}}|" -i "universal/ubi9/Dockerfile"
      - name: Display docker images
        run: docker images
      - name: Docker Build & Push Universal
        uses: docker/build-push-action@v6
        with:
          push: true
          context: universal/ubi9
          platforms: linux/amd64, linux/arm64
          tags: quay.io/abazko/universal-developer-image:pr-${{env._PR_NUMBER}}


